2024-07-20 00:19:59,098 INFO org.mathedwin.softdev.server.ChatServer: The server has been started on the port: 12345
2024-07-20 00:20:04,194 INFO org.mathedwin.softdev.server.ChatServer: The connection to a client has been accepted.
2024-07-20 00:20:04,225 INFO org.mathedwin.softdev.server.ChatServer: A customer has been added to the customer list: [org.mathedwin.softdev.server.ClientHandler@2c1b194a].
2024-07-20 00:20:04,226 INFO org.mathedwin.softdev.server.ChatServer: A new thread has been started for a customer.
2024-07-20 00:20:11,412 INFO org.mathedwin.softdev.service.RegistrationService: The username cannot be null or empty.
2024-07-20 00:20:46,728 INFO org.mathedwin.softdev.database.DBConfig: Properties successfully loaded!
2024-07-20 00:20:47,048 ERROR org.mathedwin.softdev.service.UserService: Error saving user: User(id=0, username=user3, password=password3, email=user3@example.com)
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'user3' for key 'users.unique_username'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at org.mathedwin.softdev.service.UserService.saveUser(UserService.java:128) ~[classes/:?]
	at org.mathedwin.softdev.service.RegistrationService.register(RegistrationService.java:31) ~[classes/:?]
	at org.mathedwin.softdev.server.ClientHandler.run(ClientHandler.java:102) ~[classes/:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-07-20 00:20:47,055 ERROR org.mathedwin.softdev.service.RegistrationService: Error registering user: User(id=0, username=user3, password=password3, email=user3@example.com).
org.mathedwin.softdev.exceptions.DatabaseException: Error saving user: User(id=0, username=user3, password=password3, email=user3@example.com)
	at org.mathedwin.softdev.service.UserService.saveUser(UserService.java:139) ~[classes/:?]
	at org.mathedwin.softdev.service.RegistrationService.register(RegistrationService.java:31) ~[classes/:?]
	at org.mathedwin.softdev.server.ClientHandler.run(ClientHandler.java:102) ~[classes/:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'user3' for key 'users.unique_username'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at org.mathedwin.softdev.service.UserService.saveUser(UserService.java:128) ~[classes/:?]
	... 7 more
2024-07-20 00:20:47,055 INFO org.mathedwin.softdev.server.ClientHandler: User name or email already registered.
